### ISSUE TITLE
Program shutted down after clicked ‘OK' for changing the label in Windows latest release version 

### ISSUE THREAD

**Issue by Zaoyee** [wkentaro/labelme#1002]
Program shutted down after clicked ‘OK' for changing the label in Windows latest release version. It happend for all my Windows10 system devices.

```
Traceback (most recent call last):
  File "d:\libraries\anaconda3\lib\site-packages\labelme\app.py", line 1075, in editLabel
    self._update_shape_color(shape)
  File "d:\libraries\anaconda3\lib\site-packages\labelme\app.py", line 1155, in _update_shape_color
    r, g, b = self._get_rgb_by_label(shape.label)
  File "d:\libraries\anaconda3\lib\site-packages\labelme\app.py", line 1165, in _get_rgb_by_label
    item = self.uniqLabelList.findItemsByLabel(label)[0]
IndexError: list index out of range
```

**Comment by 1193700079** [comment]
I'm having this problem too

**Comment by wkentaro** [comment]
> *This was generated by AI during triage.*

Moving to **needs-triage** (appears resolved). The crash was an `IndexError` in the old `_get_rgb_by_label`, which did `self.uniqLabelList.findItemsByLabel(label)[0]` and blew up when the (newly assigned) label wasn't yet in the unique-label list. The current `_get_rgb_by_label` (`labelme/app.py`) uses `unique_label_list.find_label_item(label)` and falls back to `unique_label_list.count()` for the color index when the item is `None`, so changing a shape's label to a brand-new value no longer crashes. Recommend closing unless editing a label still aborts.
