### ISSUE TITLE
Install on m1

### ISSUE THREAD

**Issue by XinBow99** [wkentaro/labelme#1003]
conda install pyqt
conda install matplotlib
pip install labelme
**That works for me!**

**Comment by loyio** [comment]
actually It's not work for me with miniconda, when install it with pip
and I run with `labelimg`, And then report an error.
```
Traceback (most recent call last):
  File "/Users/loyio/miniforge3/bin/labelme", line 5, in <module>
    from labelme.__main__ import main
  File "/Users/loyio/miniforge3/lib/python3.9/site-packages/labelme/__init__.py", line 17, in <module>
    QT4 = QT_VERSION[0] == "4"
TypeError: 'NoneType' object is not subscriptable
```

but I try to use the brew env, it's work
```bash
brew install pyqt@5
/opt/homebrew/bin/python3 -m pip install labelme
```
