### ISSUE TITLE
QT4 = QT_VERSION[0] == "4" I don't know how to make it work.

### ISSUE THREAD

**Issue by Solskjaer-YES** [wkentaro/labelme#1011]
(Pytorch) G:\swin\Swin-Transformer-Object-Detection-master\data\instance_segmentation>python labelme2coco.py data_annotated data_dataset_coco --labels labels.txt
Traceback (most recent call last):
  File "labelme2coco.py", line 16, in <module>
    import labelme
  File "C:\ProgramData\Anaconda3\envs\Pytorch\lib\site-packages\labelme\__init__.py", line 17, in <module>
    QT4 = QT_VERSION[0] == "4"
TypeError: 'NoneType' object is not subscriptable

**Comment by travishsu** [comment]
seems `qt` is not installed properly. try `conda install qt` or re-create env with `conda create -n new_env python=3 qt pyqt pyside2 -y`

**Comment by aurelien-m** [comment]
What worked for me without using `conda`:
```
pip install pyqt5
pip install qtpy
```

**Comment by sleepyheead** [comment]
I still can not solve this 🥹

**Comment by sleepyheead** [comment]
I got the same error. When I tried to run 'labelme' in terminal, this error appear:

Traceback (most recent call last):
  File "/usr/bin/labelme", line 33, in <module>
    sys.exit(load_entry_point('labelme==4.6.0', 'console_scripts', 'labelme')())
  File "/usr/bin/labelme", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/labelme/__init__.py", line 17, in <module>
    QT4 = QT_VERSION[0] == "4"
TypeError: 'NoneType' object is not subscriptable

**Comment by HowcanoeWang** [comment]
> seems `qt` is not installed properly. try `conda install qt` or re-create env with `conda create -n new_env python=3 qt pyqt pyside2 -y`

In case someone meet the conda pyside2 PackageNotFound error, please add conda-forge channel

`conda create -c conda-forge -n new_env python=3 qt pyqt pyside2`
