### ISSUE TITLE
The Windows version of Labelme v5.0.1 will crash abnormally when the dog.jpg picture below is opened.

### ISSUE THREAD

**Issue by yangbohust** [wkentaro/labelme#1036]
The Windows version of Labelme v5.0.1 will crash abnormally when the dog.jpg picture below is opened.

[Labelme.exe v5.0.1](https://github.com/wkentaro/labelme/releases/download/v5.0.1/Labelme.exe)
[dog.jpg](https://raw.githubusercontent.com/yangbohust/labelme_test_images/main/problematic_image/dog.jpg)

This problem is very strange. I guess it is related to the picture decoding. It is normal to open other pictures. When opening this puppy picture, it will crash abnormally.

**Comment by HowcanoeWang** [comment]
The Error log to open this image:

```python
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\labelme37\lib\site-packages\PIL\JpegImagePlugin.py", line 630, in _save
    rawmode = RAWMODE[im.mode]
KeyError: 'P'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Github\labelme\labelme\app.py", line 1750, in openFile
    self.loadFile(fileName)
  File "E:\Github\labelme\labelme\app.py", line 1514, in loadFile
    self.imageData = LabelFile.load_image_file(filename)
  File "E:\Github\labelme\labelme\label_file.py", line 66, in load_image_file
    image_pil.save(f, format=format)
  File "C:\ProgramData\Miniconda3\envs\labelme37\lib\site-packages\PIL\Image.py", line 2212, in save
    save_handler(self, fp, filename)
  File "C:\ProgramData\Miniconda3\envs\labelme37\lib\site-packages\PIL\JpegImagePlugin.py", line 632, in _save
    raise OSError(f"cannot write mode {im.mode} as JPEG") from e
OSError: cannot write mode P as JPEG
```

**Comment by sunzhaoyang** [comment]
```
from PIL import Image

Image.open('old.jpeg').convert('RGB').save('new.jpeg')
```
