### ISSUE TITLE
Crash when open the dir

### ISSUE THREAD

**Issue by NinelieAimer** [wkentaro/labelme#1201]
### Provide environment information

/d/Anaconda/envs/labeld/python
Python 3.9.13
labelme         5.0.3

### What OS are you using?

windows11

### Describe the Bug

When I open the dir, the program crash and the error:

Traceback (most recent call last):
  File "D:\Anaconda\envs\labeld\lib\site-packages\labelme\app.py", line 1112, in fileSelectionChanged
    self.loadFile(filename)
  File "D:\Anaconda\envs\labeld\lib\site-packages\labelme\app.py", line 1544, in loadFile
    self.loadLabels(self.labelFile.shapes)
  File "D:\Anaconda\envs\labeld\lib\site-packages\labelme\app.py", line 1233, in loadLabels
    self.loadShapes(s)
  File "D:\Anaconda\envs\labeld\lib\site-packages\labelme\app.py", line 1194, in loadShapes
    self.addLabel(shape)
  File "D:\Anaconda\envs\labeld\lib\site-packages\labelme\app.py", line 1139, in addLabel
    self.labelList.addItem(label_list_item)
  File "D:\Anaconda\envs\labeld\lib\site-packages\labelme\widgets\label_list_widget.py", line 167, in addItem
    item.setSizeHint(self.itemDelegate().sizeHint(None, None))
TypeError: setSizeHint(self, QSize): argument 1 has unexpected type 'QSizeF'

**Comment by wkentaro** [comment]
Thanks for the report! Will be fixed by https://github.com/wkentaro/labelme/pull/1202
