### ISSUE TITLE
Crashes because QPoint fails with latest verion

### ISSUE THREAD

**Issue by ivanlengyel** [wkentaro/labelme#1203]
### Provide environment information

```# Name                    Version                   Build  Channel
blosc                     1.21.1               hd0a9f43_0    conda-forge
brotli                    1.0.9                h5eb16cf_7    conda-forge
brotli-bin                1.0.9                h5eb16cf_7    conda-forge
brunsli                   0.1                  h046ec9c_0    conda-forge
bzip2                     1.0.8                h1de35cc_0
c-ares                    1.18.1               h0d85af4_0    conda-forge
ca-certificates           2022.4.26            hecd8cb5_0    anaconda
certifi                   2022.6.15                pypi_0    pypi
cfitsio                   3.470                h01dc385_7    conda-forge
charls                    2.2.0                h23ab428_0
cloudpickle               2.2.0              pyhd8ed1ab_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cytoolz                   0.11.0                   pypi_0    pypi
dask-core                 2022.10.0          pyhd8ed1ab_1    conda-forge
ffmpeg                    4.3.2                h4dad6da_0    conda-forge
fonttools                 4.38.0                   pypi_0    pypi
freetype                  2.10.4               h4cff582_1    conda-forge
fsspec                    2022.10.0          pyhd8ed1ab_0    conda-forge
future                    0.18.2                   pypi_0    pypi
gettext                   0.21.1               h8a4c099_0    conda-forge
giflib                    5.2.1                hbcb3906_2    conda-forge
glib                      2.69.1               h8346a28_1    anaconda
gmp                       6.2.1                h2e338ed_0    conda-forge
gnutls                    3.6.13               h756fd2b_1    conda-forge
gst-plugins-base          1.14.0               h4180768_2    anaconda
gstreamer                 1.14.0               h0fc69c2_2    anaconda
icu                       58.2                 h0a44026_3    anaconda
imagecodecs               2021.8.26                pypi_0    pypi
imageio                   2.22.0             pyhfa7a67d_0    conda-forge
imgviz                    1.5.1              pyhd8ed1ab_0    conda-forge
joblib                    1.2.0              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   hac89ed1_2    conda-forge
jxrlib                    1.1                  h35c211d_2    conda-forge
kiwisolver                1.4.4                    pypi_0    pypi
krb5                      1.19.3               hb49756b_0    conda-forge
labelme                   5.0.4                    pypi_0    pypi
lame                      3.100             hb7f2c08_1003    conda-forge
lcms2                     2.12                 h577c468_0    conda-forge
lerc                      3.0                  he49afe7_0    conda-forge
libaec                    1.0.6                he49afe7_0    conda-forge
libblas                   3.9.0           16_osx64_openblas    conda-forge
libbrotlicommon           1.0.9                h5eb16cf_7    conda-forge
libbrotlidec              1.0.9                h5eb16cf_7    conda-forge
libbrotlienc              1.0.9                h5eb16cf_7    conda-forge
libcblas                  3.9.0           16_osx64_openblas    conda-forge
libclang                  12.0.0          default_hbc2896b_2    anaconda
libcurl                   7.85.0               h6dfd666_0
libcxx                    14.0.6               h9765a3e_0
libdeflate                1.8                  h9ed2024_5
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libffi                    3.3                  hb1e8313_2
libgfortran               5.0.0           10_4_0_h97931a8_25    conda-forge
libgfortran5              11.3.0              h082f757_25    conda-forge
libiconv                  1.17                 hac89ed1_0    conda-forge
liblapack                 3.9.0           16_osx64_openblas    conda-forge
libllvm12                 12.0.0               h9b2ccf5_3    anaconda
libnghttp2                1.46.0               ha29bfda_0
libopenblas               0.3.21          openmp_h429af6e_3    conda-forge
libpng                    1.6.37               ha441bb4_0
libpq                     12.9                 h1c9f633_3    anaconda
libssh2                   1.10.0               h52ee1ee_2    conda-forge
libtiff                   4.4.0                h2ef1027_0
libwebp                   1.2.4                hfa4350a_0    conda-forge
libwebp-base              1.2.4                h775f41a_0    conda-forge
libxml2                   2.9.14               hbf8cd5e_0    anaconda
libxslt                   1.1.35               h5b33f42_0    anaconda
libzopfli                 1.0.3                h046ec9c_0    conda-forge
llvm-openmp               14.0.4               ha654fa7_0    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lz4-c                     1.9.3                he49afe7_1    conda-forge
matplotlib                3.5.3                    pypi_0    pypi
matplotlib-base           3.5.3           py310h6438751_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
natsort                   8.2.0              pyhd8ed1ab_0    conda-forge
ncurses                   6.3                  hca72f7f_3
nettle                    3.6                  hedd7734_0    conda-forge
networkx                  2.8.7              pyhd8ed1ab_0    conda-forge
nspr                      4.33                 he9d5cce_0    anaconda
nss                       3.74                 h47edf6a_0    anaconda
numpy                     1.23.4                   pypi_0    pypi
openh264                  2.1.1                h8346a28_0
openjpeg                  2.3.1                h6cbf5cd_3    conda-forge
openssl                   1.1.1q               hfd90126_1    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
partd                     1.3.0              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 h23ab428_0    anaconda
pillow                    9.2.0                    pypi_0    pypi
pip                       22.2.2                   pypi_0    pypi
ply                       3.11                     pypi_0    pypi
pyglet                    1.5.27                   pypi_0    pypi
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyqt                      5.15.7          py310he9d5cce_0
pyqt5-sip                 12.11.0                  pypi_0    pypi
python                    3.10.6               hdfd78df_1
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python.app                1.4             py310he24745e_0    conda-forge
python_abi                3.10                    2_cp310    conda-forge
pywavelets                1.3.0                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
qt-main                   5.15.2               h719ae48_7
qt-webengine              5.15.9               h90a370e_4
qtpy                      2.2.1              pyhd8ed1ab_0    conda-forge
qtwebkit                  5.212                h24dc246_4
readline                  8.2                  hca72f7f_0
scikit-image              0.19.3                   pypi_0    pypi
scikit-learn              1.1.2                    pypi_0    pypi
scipy                     1.9.3                    pypi_0    pypi
setuptools                63.4.1                   pypi_0    pypi
sip                       6.6.2                    pypi_0    pypi
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.9                h6e38e02_1    conda-forge
sqlite                    3.39.3               h707629a_0
termcolor                 2.0.1              pyhd8ed1ab_1    conda-forge
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tifffile                  2021.4.8           pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h5d9f67b_0
toml                      0.10.2             pyhd3eb1b0_0    anaconda
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tzdata                    2022e                h04d1e81_0
unicodedata2              14.0.0                   pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0
x264                      1!161.3030           h0d85af4_1    conda-forge
xz                        5.2.6                hca72f7f_0
yaml                      0.2.5                h0d85af4_2    conda-forge
zfp                       0.5.5                h4a89273_8    conda-forge
zlib                      1.2.13               h4dc903c_0
zstd                      1.5.2                hcb37349_0
```

### What OS are you using?

macOs

### Describe the Bug

Using latest version I have this error when annotating with polygons.
```
2022-10-25 15:43:29.189 python[19932:1071907] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to (null)
Traceback (most recent call last):
  File "/Users/***/miniconda3/envs/labelme/lib/python3.10/site-packages/labelme/widgets/canvas.py", line 212, in mouseMoveEvent
    pos = self.intersectionPoint(self.current[-1], pos)
  File "/Users/***/miniconda3/envs/labelme/lib/python3.10/site-packages/labelme/widgets/canvas.py", line 705, in intersectionPoint
    return QtCore.QPoint(x, y)
TypeError: arguments did not match any overloaded call:
  QPoint(): too many arguments
  QPoint(int, int): argument 1 has unexpected type 'float'
  QPoint(QPoint): argument 1 has unexpected type 'float'
```

### Expected Behavior

no fail

**Comment by wkentaro** [comment]
released v5.0.5

```
pip install --no-cache-dir -U labelme
```
