### ISSUE TITLE
Polygons cannot cover the entire canvas

### ISSUE THREAD

**Issue by sergiud** [wkentaro/labelme#1226]
### Provide environment information

/usr/bin/python
Python 3.10.9
labelme 2b225b2b384bdb25fb37678a9d28b8e545732473

### What OS are you using?

ArchLinux

### Describe the Bug

While creating polygons, it is not possible to set vertices along the right/bottom edges of the canvas.

Consider the following example and notice the bottom right corner. The points cannot be moved any further towards the nearest edge:
![Screenshot from 2023-01-11 16-13-36](https://user-images.githubusercontent.com/2170034/211849643-71fd0844-3d1f-4ff3-801d-4eac3f6fe785.png)

The culprit seems to be the following method that sets the bounds of the canvas one pixel short:

https://github.com/wkentaro/labelme/blob/2b225b2b384bdb25fb37678a9d28b8e545732473/labelme/widgets/canvas.py#L719-L743

For some reason (probably this is related to the use of the pixmap), the method assumes integral coordinates. However, since the canvas is not defined by an integer grid, the set of possible coordinates is given by $(x,y) \in [0, \text{width}[ \times [0, \text{height}[$ (assuming the pixel origin to be in the top-right corner), i.e., the width and the height define the upper bound along each axis instead of width/height minus one.

The following patch solves the problem for me:
```patch
diff --git a/labelme/widgets/canvas.py b/labelme/widgets/canvas.py
index cc77db5..7d63d79 100644
--- a/labelme/widgets/canvas.py
+++ b/labelme/widgets/canvas.py
@@ -697,7 +697,7 @@ class Canvas(QtWidgets.QWidget):
 
     def outOfPixmap(self, p):
         w, h = self.pixmap.width(), self.pixmap.height()
-        return not (0 <= p.x() <= w - 1 and 0 <= p.y() <= h - 1)
+        return not (0 <= p.x() < w and 0 <= p.y() < h)
 
     def finalise(self):
         assert self.current
@@ -723,13 +723,13 @@ class Canvas(QtWidgets.QWidget):
         size = self.pixmap.size()
         points = [
             (0, 0),
-            (size.width() - 1, 0),
-            (size.width() - 1, size.height() - 1),
-            (0, size.height() - 1),
+            (size.width(), 0),
+            (size.width(), size.height()),
+            (0, size.height()),
         ]
         # x1, y1 should be in the pixmap, x2, y2 should be out of the pixmap
-        x1 = min(max(p1.x(), 0), size.width() - 1)
-        y1 = min(max(p1.y(), 0), size.height() - 1)
+        x1 = min(max(p1.x(), 0), size.width())
+        y1 = min(max(p1.y(), 0), size.height())
         x2, y2 = p2.x(), p2.y()
         d, i, (x, y) = min(self.intersectingEdges((x1, y1), (x2, y2), points))
         x3, y3 = points[i]

```

### Expected Behavior

Polygon vertices should be placeable along the bottom and the right edge.

Applying the above patch makes it possible to achieve this:

![Screenshot from 2023-01-11 18-34-44](https://user-images.githubusercontent.com/2170034/211877791-95e354f3-64da-408d-9957-bf05bbec28f8.png)

### To Reproduce

Create a polygon and try placing points at the bottom right edges of the canvas.

**Comment by monkeycc** [comment]
```python
Traceback (most recent call last):
  File "D:\anaconda3\Lib\site-packages\labelme\widgets\canvas.py", line 574, in mouseDoubleClickEvent
    self.finalise()
  File "D:\anaconda3\Lib\site-packages\labelme\widgets\canvas.py", line 808, in finalise
    assert self.current
           ^^^^^^^^^^^^
AssertionError
```

**Comment by sergiud** [comment]
@monkeycc I've no idea what are you trying to communicate.

**Comment by wkentaro** [comment]
> *This was generated by AI during triage.*

Moving to **needs-triage** (appears resolved). The "one pixel short" bound the report points at is gone: the current `_is_out_of_image` uses strict `>` comparisons (`point.x() > width()`, `point.y() > height()`), so a vertex at exactly the right/bottom edge - including the bottom-right corner `(width, height)` - is in-bounds and reachable. I verified the edge-clamp (`_compute_intersection_edges_image`) returns coordinates up to and including the full image extent. Recommend closing unless the last row/column is still unreachable.
