### ISSUE TITLE
 if self._config[dock]['closable']: TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by zombieMaybeLikeCake** [wkentaro/labelme#1239]
### Provide environment information

Python 3.5.6 :: Anaconda, Inc.
certifi (2020.6.20)
cycler (0.10.0)
kiwisolver (1.1.0)
labelme (3.16.2)
matplotlib (3.0.3)
numpy (1.18.5)
olefile (0.46)
Pillow (5.2.0)
pip (20.3.4)
pyparsing (2.4.7)
PyQt5 (5.15.2)
PyQt5-sip (12.9.1)
python-dateutil (2.8.2)
PyYAML (5.3.1)
QtPy (1.9.0)
setuptools (40.2.0)
six (1.16.0)
termcolor (1.1.0)
wheel (0.37.1)
wincertstore (0.2)

### What OS are you using?

windows 10

### Describe the Bug

Traceback (most recent call last):
  File "c:\users\robert\.conda\envs\labelme\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\robert\.conda\envs\labelme\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\robert\.conda\envs\labelme\Scripts\labelme.exe\__main__.py", line 9, in <module>
  File "c:\users\robert\.conda\envs\labelme\lib\site-packages\labelme\main.py", line 164, in main
    output_dir=output_dir,
  File "c:\users\robert\.conda\envs\labelme\lib\site-packages\labelme\app.py", line 166, in __init__
    if self._config[dock]['closable']:
TypeError: 'NoneType' object is not subscriptable

### To Reproduce

conda create–name=labelme python=3.9

 conda activate labelme

pip install pyqt5

conda install pillow
 pip install labelme==3.16.2

**Comment by ignpaub** [comment]
Same error by here. In this case with labelme==5.2.1

**Comment by jessie900309** [comment]
I followed your instructions to add `.labelmerc` in the `anaconda3\envs\labelme\Lib\site-packages\labelme` directory, but I still encounter the following error when executing `labelme`:

```Traceback (most recent call last):
  File "C:\Users\zombie\anaconda3\envs\labelme\Scripts\labelme-script.py", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\Users\zombie\anaconda3\envs\labelme\Lib\site-packages\labelme\__main__.py", line 172, in main
    win = MainWindow(
          ^^^^^^^^^^^
  File "C:\Users\zombie\anaconda3\envs\labelme\Lib\site-packages\labelme\app.py", line 197, in __init__
    if self._config[dock]["closable"]:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable```

Sorry if I make any mistake in my english.

**Comment by wkentaro** [comment]
> *This was generated by AI during triage.*

Re-triaged following @JessieOuO's 2024-02-19 report of the identical traceback.

**This crash no longer reproduces on current `main`.** Verified by loading a config file with an empty dock section:

```yaml
label_dock:
```

Previously this replaced the whole `label_dock` section with `None`, so the later `self._config[dock]["closable"]` lookup raised `TypeError: 'NoneType' object is not subscriptable` before the window ever appeared. On `main` the merge now keeps the section defaults instead of wiping them, and the config loads to `{'show': True, 'closable': True, 'movable': True, 'floatable': True}` with no crash. That fix landed via #2295.

A malformed section of the wrong *type* (e.g. `label_dock: oops`) is also handled now: it raises a clean `ValueError` naming the offending section, which surfaces in the configuration-error dialog and falls back to defaults rather than terminating the app.

**Practical note for anyone who lands here from a search:** the crash means your `~/.labelmerc` has a dock section that is empty or not a mapping. Either delete the file to fall back to defaults, or give each dock section its keys explicitly:

```yaml
label_dock:
  show: true
  closable: true
  movable: true
  floatable: true
```

**Parking this in `needs-triage` for the maintainer**, since the underlying defect is fixed but closing an issue is not this pass's call. @wkentaro — this looks closeable as fixed by #2295.
