### ISSUE TITLE
Invalid base64-encoded string: number of data characters (158533) cannot be 1 more than a multiple of 4

### ISSUE THREAD

**Issue by enamulrafti** [wkentaro/labelme#1275]
### Discussed in https://github.com/wkentaro/labelme/discussions/1274

<div type='discussions-op-text'>

<sup>Originally posted by **enamulrafti** May  8, 2023</sup>
### **While executing labelme2coco.py I am facing the issue. The issue is:** 

_Traceback (most recent call last):
  File "C:\Users\User\anaconda3\lib\site-packages\labelme\label_file.py", line 108, in load
    imageData = base64.b64decode(data["imageData"])
  File "C:\Users\User\anaconda3\lib\base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (158533) cannot be 1 more than a multiple of 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\iar\prepocessing-codes\labelme2coco.py", line 222, in <module>
    main()
  File "F:\iar\prepocessing-codes\labelme2coco.py", line 107, in main
    label_file = labelme.LabelFile(filename=filename)
  File "C:\Users\User\anaconda3\lib\site-packages\labelme\label_file.py", line 44, in __init__
    self.load(filename)
  File "C:\Users\User\anaconda3\lib\site-packages\labelme\label_file.py", line 138, in load
    raise LabelFileError(e)
labelme.label_file.LabelFileError: Invalid base64-encoded string: number of data characters (158533) cannot be 1 more than a multiple of 4_

### **and i have checked line no 108 in labelme.py which shows:** 
`imageData = base64.b64decode(data["imageData"])`

### **which i have tried to replace with this line:** 
`imageData = base64.b64decode(data["imageData"] + '==')`
### which show this error: 
_Traceback (most recent call last):
  File "C:\Users\User\anaconda3\lib\site-packages\labelme\label_file.py", line 109, in load
    imageData = base64.b64decode(data["imageData"] + '==')
  File "C:\Users\User\anaconda3\lib\base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (678697) cannot be 1 more than a multiple of 4_

**Help me! thanks in advance.**</div>

**Comment by wkentaro** [comment]
> *This was generated by AI during triage.*

## Triage Notes

**What we've established so far:**

- The traceback shows `labelme.LabelFile(filename=filename)` being called directly from a custom script (`labelme2coco.py`), not from the labelme GUI, and the failure comes from `base64.b64decode()` choking on a corrupted or truncated `imageData` string inside the `.json` file.
- On current labelme, opening a `.json` file with corrupted `imageData` through the GUI is handled gracefully: you get an "Error opening file" dialog instead of a crash. The class-based `labelme.LabelFile` API used in the traceback no longer exists either, since the loading logic moved to internal functions.
- Padding the base64 string with `==` produced a different base64 error, which suggests the `imageData` content itself is truncated or corrupted rather than merely missing padding.

**What we still need from you (@enamulrafti):**

- Could you attach one of the `.json` files that fails to load, or a minimal one that reproduces it? Seeing the actual `imageData` content is what distinguishes a labelme writing bug from corruption after the fact.
- What produced this `.json` file: was it saved directly by labelme, or did it pass through another tool or script before the failure?
- Do you know of anything that could have interrupted or modified the file (process killed while saving, disk full, manual edits, a merge)?
