### ISSUE TITLE
Problem encountered when using fast-scnn

### ISSUE THREAD

**Issue by SummerTide** [wkentaro/labelme#1328]
### Provide environment information

~/anaconda3/envs/pytorch/bin/python
--------------------------- --------------- ---------------------------
Python 3.7.13
--------------------------- --------------- ---------------------------
Package                     Version         Editable project location

absl-py                     1.4.0
addict                      2.4.0
affine                      2.4.0
aiohttp                     3.8.5
aiosignal                   1.3.1
albumentations              1.3.1
aliyun-python-sdk-core      2.13.36
aliyun-python-sdk-kms       2.16.1
anykeystore                 0.2
async-timeout               4.0.3
asynctest                   0.13.0
attrs                       23.1.0
blessed                     1.20.0
cachetools                  5.3.1
certifi                     2022.12.7
cffi                        1.15.1
changeos                    0.2
charset-normalizer          3.2.0
click                       8.1.6
click-plugins               1.1.1
cligj                       0.7.2
colorama                    0.4.6
crcmod                      1.7
cryptacular                 1.6.2
cryptography                41.0.3
cxxfilt                     0.3.0
cycler                      0.11.0
defusedxml                  0.7.1
efficientnet-pytorch        0.7.1
ever-beta                   0.2.3
exceptiongroup              1.1.2
filelock                    3.12.2
Fiona                       1.9.4.post1
flit_core                   3.6.0
fonttools                   4.38.0
frozenlist                  1.3.3
fsspec                      2023.1.0
GDAL                        3.4.1
geopandas                   0.10.2
google-auth                 2.23.0
google-auth-oauthlib        0.4.6
gpustat                     1.0.0
greenlet                    2.0.2
grpcio                      1.58.0
huggingface-hub             0.16.4
hupper                      1.12
idna                        3.4
imageio                     2.31.1
importlib-metadata          6.7.0
iniconfig                   2.0.0
install                     1.3.5
jmespath                    0.10.0
joblib                      1.3.1
kiwisolver                  1.4.4
lightning-utilities         0.9.0
Markdown                    3.4.4
markdown-it-py              2.2.0
MarkupSafe                  2.1.3
matplotlib                  3.5.3
mdurl                       0.1.2
mkl-fft                     1.3.1
mkl-random                  1.2.2
mkl-service                 2.4.0
mmcv                        2.0.0
mmdet                       3.1.0
mmengine                    0.8.4
mmsegmentation              1.1.1           /data1/gjc23/mmsegmentation
model-index                 0.1.11
multidict                   6.0.4
munch                       4.0.0
networkx                    2.6.3
ninja                       1.11.1
numpy                       1.21.5
nvidia-cublas-cu11          11.10.3.66
nvidia-cuda-nvrtc-cu11      11.7.99
nvidia-cuda-runtime-cu11    11.7.99
nvidia-cudnn-cu11           8.5.0.96
nvidia-ml-py                11.495.46
oauthlib                    3.2.2
opencv-python               4.8.0.74
opencv-python-headless      4.8.0.76
opendatalab                 0.0.10
openmim                     0.3.9
openxlab                    0.0.10
ordered-set                 4.1.0
oss2                        2.17.0
packaging                   23.1
pandas                      1.3.5
PasteDeploy                 3.0.1
pbkdf2                      1.3
Pillow                      9.0.1
pip                         22.3.1
plaster                     1.1.2
plaster-pastedeploy         1.0.1
platformdirs                3.10.0
pluggy                      1.2.0
pretrainedmodels            0.7.4
prettytable                 3.7.0
protobuf                    3.20.3
psutil                      5.9.5
pyasn1                      0.5.0
pyasn1-modules              0.3.0
pycocotools                 2.0.7
pycparser                   2.21
pycryptodome                3.18.0
Pygments                    2.16.1
pyparsing                   3.1.1
pyproj                      3.2.1
pyramid                     2.0.1
pyramid-mailer              0.15.1
pytest                      7.4.0
python-dateutil             2.8.2
python3-openid              3.2.0
pytorch-lightning           1.9.5
pytz                        2023.3
PyWavelets                  1.3.0
PyYAML                      6.0.1
qudida                      0.0.4
rasterio                    1.2.10
repoze.sendmail             4.4.1
requests                    2.28.2
requests-oauthlib           1.3.1
rich                        13.5.2
rsa                         4.9
safetensors                 0.3.3
scikit-image                0.19.3
scikit-learn                1.0.2
scipy                       1.7.3
seaborn                     0.12.2
segmentation-models-pytorch 0.3.3
setuptools                  60.2.0
shapely                     2.0.1
six                         1.16.0
snuggs                      1.4.7
SQLAlchemy                  2.0.19
tabulate                    0.9.0
tensorboard                 2.11.2
tensorboard-data-server     0.6.1
tensorboard-plugin-wit      1.8.1
tensorboardX                2.6.2.2
termcolor                   2.3.0
terminaltables              3.1.10
threadpoolctl               3.1.0
tifffile                    2021.11.2
timm                        0.9.2
tomli                       2.0.1
torch                       1.10.1+cu113
torchaudio                  0.7.0a0+a853dff
torchmetrics                0.11.4
torchvision                 0.11.2+cu113
tqdm                        4.65.0
transaction                 3.1.0
translationstring           1.4
typing_extensions           4.7.1
urllib3                     1.26.16
velruse                     1.1.1
venusian                    3.0.0
wcwidth                     0.2.6
WebOb                       1.8.7
Werkzeug                    2.2.3
wheel                       0.38.4
WTForms                     3.0.1
wtforms-recaptcha           0.3.2
yapf                        0.40.1
yarl                        1.9.2
zipp                        3.15.0
zope.deprecation            5.0
zope.interface              6.0
zope.sqlalchemy             3.0

### What OS are you using?

CentOS & Win10

### Describe the Bug

I try to build the config file of the fast-fscnn with my own dataset, but when calculating accuracy, I encountered a CUDA erroe,.
The specific error message is as follows:
`
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:93: operator(): block: [3809,0,0], thread: [57,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File "tools/train.py", line 104, in <module>
    main()
  File "tools/train.py", line 100, in main
    runner.train()
  File "/home/gjc23/anaconda3/envs/pytorch/lib/python3.7/site-packages/mmengine/runner/runner.py", line 1745, in train
    model = self.train_loop.run()  # type: ignore
  File "/home/gjc23/anaconda3/envs/pytorch/lib/python3.7/site-packages/mmengine/runner/loops.py", line 278, in run
    self.run_iter(data_batch)
  File "/home/gjc23/anaconda3/envs/pytorch/lib/python3.7/site-packages/mmengine/runner/loops.py", line 302, in run_iter
    data_batch, optim_wrapper=self.runner.optim_wrapper)
  File "/home/gjc23/anaconda3/envs/pytorch/lib/python3.7/site-packages/mmengine/model/base_model/base_model.py", line 114, in train_step
    losses = self._run_forward(data, mode='loss')  # type: ignore
  File "/home/gjc23/anaconda3/envs/pytorch/lib/python3.7/site-packages/mmengine/model/base_model/base_model.py", line 340, in _run_forward
    results = self(**data, mode=mode)
  File "/home/gjc23/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data1/gjc23/mmsegmentation/mmseg/models/segmentors/base.py", line 94, in forward
    return self.loss(inputs, data_samples)
  File "/data1/gjc23/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 178, in loss
    loss_decode = self._decode_head_forward_train(x, data_samples)
  File "/data1/gjc23/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 140, in _decode_head_forward_train
    self.train_cfg)
  File "/data1/gjc23/mmsegmentation/mmseg/models/decode_heads/decode_head.py", line 262, in loss
    losses = self.loss_by_feat(seg_logits, batch_data_samples)
  File "/data1/gjc23/mmsegmentation/mmseg/models/decode_heads/decode_head.py", line 337, in loss_by_feat
    seg_logits, seg_label, ignore_index=self.ignore_index)
  File "/data1/gjc23/mmsegmentation/mmseg/models/losses/accuracy.py", line 49, in accuracy
    correct = correct[:, target != ignore_index]
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
`
What confuses me is that using the same dataset, I use the same method to build the config files of deeplabv3p, pspnet and mobilenetv3 and they can all be executes successfully.

### To Reproduce

This is the log file of fast-scnn on my dataset.
[20230917_102119.log](https://github.com/wkentaro/labelme/files/12641928/20230917_102119.log)
This is the log file of mobilenetv3 on my dataset.
[20230916_193704.log](https://github.com/wkentaro/labelme/files/12641930/20230916_193704.log)

**Comment by SummerTide** [comment]
Looking forward to your reply, thank you!
