### ISSUE TITLE
Crash while adjusting mask shape

### ISSUE THREAD

**Issue by rememberBr** [wkentaro/labelme#1331]
### Provide environment information

python=3.9.1
labelme = I tested both 5.2.1 and 5.3.1 with this issue

### What OS are you using?

win10

### Describe the Bug

I encountered an error while using labelme to label the mask, as follows:

Traceback (most recent call last):
  File "d:\program\miniconda\lib\site-packages\labelme\widgets\canvas.py", line 974, in keyReleaseEvent
    index = self.shapes.index(self.selectedShapes[0])
ValueError: <labelme.shape.Shape object at 0x000001DE55C0C3D0> is not in list

Occasionally, when adjusting the mask shape, there is a chance of this problem occurring in multiple versions

### Expected Behavior

Sometimes, when adjusting the shape of the mask (such as deleting certain points or moving certain points), this issue may occur

**Comment by rememberBr** [comment]
supplement：

Traceback (most recent call last):
  File "d:\program\miniconda\lib\site-packages\labelme\widgets\canvas.py", line 323, in mouseMoveEvent
    self.boundedMoveVertex(pos)
  File "d:\program\miniconda\lib\site-packages\labelme\widgets\canvas.py", line 627, in boundedMoveVertex
    point = shape[index]
  File "d:\program\miniconda\lib\site-packages\labelme\shape.py", line 352, in __getitem__
    return self.points[key]
IndexError: list index out of range

**Comment by mafeng199325** [comment]
Is there a solution

**Comment by pgmsuper** [comment]
add try...except to skip error

**Comment by wkentaro** [comment]
> *This was generated by AI during triage.*

## Triage Notes

Both crashes reported here have since been fixed, and both fixes were verified against current `main` during this triage.

**What we established:**

- The `ValueError: <Shape ...> is not in list` from the issue body (raised while resolving the selected shape's index on key release) is a duplicate of #1488, fixed by #1871.
- The `IndexError: list index out of range` added in the 2023-09-28 follow-up (raised indexing a shape's points during a bounded vertex move) is a duplicate of #1669, fixed by #1818.
- Neither fix referenced this issue, which is why it stayed open.
- Verified on current `main`: driving a bounded vertex move with an out-of-range vertex index now logs `vertex_index is out of range` and returns early instead of raising; resolving a pending moved shape that is no longer in the shape list now returns `None` instead of raising `ValueError`. Both paths have passing unit tests (`tests/unit/widgets/canvas_test.py`, 6 passed).

The implicated code was substantially refactored since v5.2.1, but the guard clauses survived the refactor intact.

**Recommendation for the maintainer:** close as fixed / duplicate of #1488 and #1669. Moving to `needs-triage` for your call rather than closing it here.

@rememberBr @mafeng199325 @pgmsuper — if either crash still reproduces on the current release, please reopen with the traceback and we will take another look.
