### ISSUE TITLE
Application crashes in Ubuntu 22.04

### ISSUE THREAD

**Issue by jesstytam** [wkentaro/labelme#1371]
### Provide environment information

/home/user/mambaforge/bin/python
Python 3.10.10

### What OS are you using?

Ubuntu 22.04

### Describe the Bug

I ran `sudo apt-get install labelme` to install the application and then ran `labelme` to open it, but after a few seconds of opening, it crashed.

Here is the error from the terminal:
```
[INFO   ] __init__:get_config:70 - Loading config file from: /home/user/.labelmerc
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/labelme/widgets/canvas.py", line 618, in paintEvent
    p.translate(self.offsetToCenter())
  File "/usr/lib/python3/dist-packages/labelme/widgets/canvas.py", line 659, in offsetToCenter
    return QtCore.QPoint(x, y)
TypeError: arguments did not match any overloaded call:
  QPoint(): too many arguments
  QPoint(int, int): argument 1 has unexpected type 'float'
  QPoint(QPoint): argument 1 has unexpected type 'float'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_labelme.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/labelme/widgets/canvas.py", line 618, in paintEvent
    p.translate(self.offsetToCenter())
  File "/usr/lib/python3/dist-packages/labelme/widgets/canvas.py", line 659, in offsetToCenter
    return QtCore.QPoint(x, y)
TypeError: arguments did not match any overloaded call:
  QPoint(): too many arguments
  QPoint(int, int): argument 1 has unexpected type 'float'
  QPoint(QPoint): argument 1 has unexpected type 'float'
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QPainter::begin: Painter already active
Segmentation fault (core dumped)
```

**Comment by sc0v0ne** [comment]
@jesstytam Good afternoon, I use brew, I had the same problem. I used brew successfully.

**Comment by wkentaro** [comment]
> *This was generated by AI during triage.*

Re-triaged following the 2023-12-19 replies, which were never followed up.

## Triage Notes

**What we've established so far:**

- Your traceback is specific and credible: a float reached a `QPoint` constructor that only accepts ints, the exception escaped `paintEvent`, and PyQt5 turned that into `Segmentation fault (core dumped)`. The segfault is a consequence of the `TypeError`, not a separate fault.
- @step305's int-cast suggestion was on target for the code as it stood then.
- However, the reported crash site no longer exists. The canvas was rewritten since this report: the centering offset is now computed as a float-typed point and passed straight to `painter.translate()`, which accepts floats natively, and the remaining `QPoint` constructions in that module already cast explicitly. So this specific defect appears to have been fixed as a byproduct of the rewrite, but we cannot confirm that from here without a retest.
- @sc0v0ne's Homebrew suggestion is a workaround by avoidance, not a fix: it sidesteps the problem by pulling a different Qt build. It does not explain the failure and does not apply well to Ubuntu.
- Relevant to your install: `apt-get install labelme` is a third-party Debian/Ubuntu package, not a distribution this project maintains, and it is typically far behind. The supported paths are `pip` and the standalone executable. Current labelme also requires Python 3.12+ (you reported 3.10.10) and uses PySide6 rather than PyQt5.
- Checked against other Linux launch failures and none is the same defect: #1220 fails at Qt platform-plugin load before any painting, #889 segfaults natively with no Python traceback at all, #1546 is a Python-3.8 syntax incompatibility on Windows, #1442 is a WSL focus issue.

**What we still need from you (@jesstytam):**

- Does this still happen with a current, pip-installed labelme? Please install into a Python 3.12+ environment via `pip install -U labelme` (not the `apt` package) and confirm.
- If it still crashes, paste the new traceback in full, plus `labelme --version`.
- What exactly triggers it: does it crash on launch with no image, after opening an image, or after zooming/panning/resizing the window? Your report says "after a few seconds" without an action, which we cannot reproduce blind.
- Are you on X11 or Wayland? `echo $XDG_SESSION_TYPE`.

If the pip install works, this can be closed as fixed by the canvas rewrite.
