### ISSUE TITLE
icon file cause pyinstaller failed on windows

### ISSUE THREAD

**Issue by xikuibin** [wkentaro/labelme#145]
When try to build a standalone exe on windows, one exception is raised.

```
12702 INFO: Building EXE from out00-EXE.toc
12706 INFO: SRCPATH [('labelme/icons/icon.icns', None)]
12706 INFO: Updating icons from labelme/icons/icon.icns to C:\Users\user\AppData\Local\Temp\tmpp1wwf9ba
Traceback (most recent call last):
  File "c:\miniconda3\envs\labelme-buid\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\miniconda3\envs\labelme-buid\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Miniconda3\envs\labelme-buid\Scripts\pyinstaller.exe\__main__.py", line 9, in <module>
  File "c:\miniconda3\envs\labelme-buid\lib\site-packages\PyInstaller\__main__.py", line 94, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\miniconda3\envs\labelme-buid\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\miniconda3\envs\labelme-buid\lib\site-packages\PyInstaller\building\build_main.py", line 791, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\miniconda3\envs\labelme-buid\lib\site-packages\PyInstaller\building\build_main.py", line 737, in build
    exec(text, spec_namespace)
  File "<string>", line 37, in <module>
  File "c:\miniconda3\envs\labelme-buid\lib\site-packages\PyInstaller\building\api.py", line 420, in __init__
    self.__postinit__()
  File "c:\miniconda3\envs\labelme-buid\lib\site-packages\PyInstaller\building\datastruct.py", line 161, in __postinit__
    self.assemble()
  File "c:\miniconda3\envs\labelme-buid\lib\site-packages\PyInstaller\building\api.py", line 509, in assemble
    icon.CopyIcons(tmpnm, self.icon)
  File "c:\miniconda3\envs\labelme-buid\lib\site-packages\PyInstaller\utils\win32\icon.py", line 173, in CopyIcons
    hsrc = win32api.LoadLibraryEx(srcpath, 0, LOAD_LIBRARY_AS_DATAFILE)
pywintypes.error: (193, 'LoadLibraryEx', '%1 is not a valid Win32 application.')
```

The exception is caused by icon file specified in labelme.spec. icon.icns is mac icon format. So pyinstaller could not create exe with this file.

If convert it to windows format (.ico), the build process is sucessful.

**Comment by wkentaro** [comment]
I think https://github.com/wkentaro/labelme/pull/146 fixes this, so could you try the code on master?
