### ISSUE TITLE
labelme2voc.py  cannot identify image file

### ISSUE THREAD

**Issue by zhanghengChina** [wkentaro/labelme#164]
Thanks for sharing the code, it really helps me a lot.
However, when I run the code ./labelme2voc.py labels.txt data_annotated data_dataset_voc, it occured an error shown below:
`Traceback (most recent call last):
  File "./labelme2voc.py", line 103, in <module>
    main()
  File "./labelme2voc.py", line 98, in main
    lbl, img, label_names, colormap=colormap)
  File "/home/leon/tensorflow/fcn/FCN_train/labelme/labelme/utils.py", line 133, in draw_label
    out = PIL.Image.open(f)
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 2028, in open
    raise IOError("cannot identify image file")
IOError: cannot identify image file
`
which shows me that cannot identify image file, please tell me how can I change the code, thanks.

**Comment by wkentaro** [comment]
labelme requires `Pillow>=2.8.0`. Please check it by `pip show Pillow`

**Comment by zhanghengChina** [comment]
Thanks a lot.

**Comment by Ashlyn0628** [comment]
My pillow's version is 5.2 but I still have the same mistakes.

**Comment by starkcn** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'data_annotated/../images/320.jpg'

pillow message
Name: Pillow
Version: 6.1.0
Summary: Python Imaging Library (Fork)
Home-page: http://python-pillow.org
Author: Alex Clark (Fork Author)
Author-email: aclark@aclark.net
License: UNKNOWN
