### ISSUE TITLE
PIL installed via pip cannot be imported on Travis

### ISSUE THREAD

**Issue by wkentaro** [wkentaro/labelme#183]
```
Traceback (most recent call last):
  File "labelme/app.py", line 15, in <module>
    from labelme import __appname__
  File "/Users/travis/miniconda/envs/test/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "labelme/__init__.py", line 14, in <module>
    from labelme import testing
  File "/Users/travis/miniconda/envs/test/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "labelme/testing.py", line 4, in <module>
    import labelme.utils
  File "/Users/travis/miniconda/envs/test/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "labelme/utils.py", line 6, in <module>
    import PIL.Image
  File "/Users/travis/miniconda/envs/test/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/PIL/Image.py", line 64, in <module>
  File "/Users/travis/miniconda/envs/test/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 714, in load_module
    module = loader.load_module(fullname)
ImportError: dlopen(/var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/_MEIZHGinu/PIL._imaging.so, 2): Library not loaded: @loader_path/libjpeg.9.dylib
  Referenced from: /var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/_MEIZHGinu/PIL._imaging.so
  Reason: Incompatible library version: PIL._imaging.so requires version 13.0.0 or later, but libjpeg.9.dylib provides version 12.0.0
[3356] Failed to execute script app
```

**Comment by wkentaro** [comment]
PIL must be installed via conda for pyinstaller.
