### ISSUE TITLE
ImportError: cannot import name 'resources'

### ISSUE THREAD

**Issue by wangyarui** [wkentaro/labelme#190]
It may miss the file ''resources''??
```
Traceback (most recent call last):
  File "/usr/local/bin/labelme", line 11, in <module>
    load_entry_point('labelme==2.7.0', 'console_scripts', 'labelme')()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/labelme/app.py", line 44, in <module>
    from labelme import resources
ImportError: cannot import name 'resources'

```
Thanks very much for your reply.

**Comment by wkentaro** [comment]
You need to upgrade labelme: `pip install -U labelme`.
