### ISSUE TITLE
crash on my mac : assert len(items) == 1

### ISSUE THREAD

**Issue by duchengyao** [wkentaro/labelme#283]
```
Traceback (most recent call last):
  File "/Users/s1nh/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/labelme/app.py", line 994, in newShape
    text = self.labelDialog.popUp(text)
  File "/Users/s1nh/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/labelme/widgets/label_dialog.py", line 141, in popUp
    assert len(items) == 1
AssertionError
Abort trap: 6
```

**Comment by hongsworld** [comment]
I also experienced the same crush on windows. 
Then, I commented out that line and it works.
```python
assert len(items) == 1
```
Because the length of `items` is 2, the AssertationError is raised. 
The below codes use the first element of the items, so I commented out assert line.  
However, I do not know whether there is any problem caused by the line commented out.

**Comment by wkentaro** [comment]
It seems relaxing this assertion would be better.
