### ISSUE TITLE
IOError: cannot identify image file

### ISSUE THREAD

**Issue by wylqq312715289** [wkentaro/labelme#33]
Traceback (most recent call last):    main()
    img = utils.img_b64_to_array(data['imageData'])
  File "build\bdist.win-amd64\egg\labelme\utils.py", line 39, in img_b64_to_array
  File "E:\Anaconda2\lib\site-packages\PIL\Image.py", line 1980, in open
    raise IOError("cannot identify image file")
IOError: cannot identify image file

how could I do?

**Comment by wkentaro** [comment]
I have no idea. Probably you should provide more detail commands and procedures to reproduce the error.
