### ISSUE TITLE
when I use labelme_json_to_dataset typeerros happen

### ISSUE THREAD

**Issue by silvercherry** [wkentaro/labelme#379]
when I labelme_json_to_dataset it will
Traceback (most recent call last):
  File "c:\users\thinkpad\anaconda3\envs\lableme\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\thinkpad\anaconda3\envs\lableme\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\ThinkPAD\Anaconda3\envs\lableme\Scripts\labelme_json_to_dataset.exe\__main__.py", line 9, in <module>
  File "c:\users\thinkpad\anaconda3\envs\lableme\lib\site-packages\labelme\cli\json_to_dataset.py", line 61, in main
    utils.lblsave(osp.join(out_dir, 'label.png'), lbl)
  File "c:\users\thinkpad\anaconda3\envs\lableme\lib\site-packages\labelme\utils\_io.py", line 18, in lblsave
    lbl_pil.putpalette((colormap * 255).astype(np.uint8).flatten())
  File "c:\users\thinkpad\anaconda3\envs\lableme\lib\site-packages\PIL\Image.py", line 1654, in putpalette
    data = bytes(data)
TypeError: only integer scalar arrays can be converted to a scalar index
I do not know how to solve it

**Comment by wkentaro** [comment]
You run below command?

```
cd examples/tutorial
labelme_json_to_dataset apc2016_obj3.json
```

**Comment by ankit-gitscience** [comment]
@silvercherry  Did you get the fix for this error?
