### ISSUE TITLE
Error in Travis CI

### ISSUE THREAD

**Issue by wkentaro** [wkentaro/labelme#465]
```
Traceback (most recent call last):
  File "labelme/main.py", line 10, in <module>
    from labelme import __appname__
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "labelme/__init__.py", line 22, in <module>
    from labelme import testing
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "labelme/testing.py", line 4, in <module>
    import labelme.utils
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "labelme/utils/__init__.py", line 3, in <module>
    from ._io import lblsave
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "labelme/utils/_io.py", line 3, in <module>
    import numpy as np
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/numpy/__init__.py", line 150, in <module>
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/numpy/random/__init__.py", line 180, in <module>
  File "mtrand.pyx", line 1, in init numpy.random.mtrand
ModuleNotFoundError: No module named 'numpy.random.common'
[7879] Failed to execute script main
The command "if [ "$RUN_PYINSTALLER" = "true" ]; then
```

**Comment by wkentaro** [comment]
Had another problem:

Had this problem with pyside2==5.12.4

```
$ pytest -v tests
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/_pytest/main.py", line 202, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/_pytest/config/__init__.py", line 671, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/pluggy/hooks.py", line 311, in call_historic
INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/pluggy/manager.py", line 87, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/pluggy/manager.py", line 81, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/pluggy/callers.py", line 81, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/pytestqt/plugin.py", line 228, in pytest_configure
INTERNALERROR>     QtBot._inject_qtest_methods()
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/pytestqt/qtbot.py", line 645, in _inject_qtest_methods
INTERNALERROR>     method = create_qtest_proxy_method(method_name)
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/pytestqt/qtbot.py", line 624, in create_qtest_proxy_method
INTERNALERROR>     functools.update_wrapper(result, qtest_method)
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/functools.py", line 32, in update_wrapper
INTERNALERROR>     for attr in assigned:
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/shiboken2/files.dir/shibokensupport/signature/parser.py", line 286, in pyside_type_init
INTERNALERROR>     update_mapping()
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/shiboken2/files.dir/shibokensupport/signature/mapping.py", line 233, in update
INTERNALERROR>     candidates = list(mod_name for mod_name in sys.modules
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/shiboken2/files.dir/shibokensupport/signature/mapping.py", line 233, in <genexpr>
INTERNALERROR>     candidates = list(mod_name for mod_name in sys.modules
INTERNALERROR> RuntimeError: dictionary changed size during iteration
The command "pytest -v tests" exited with 3.
```Had this problem with pyside2==5.12.4

```
$ pytest -v tests
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/_pytest/main.py", line 202, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/_pytest/config/__init__.py", line 671, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/pluggy/hooks.py", line 311, in call_historic
INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/pluggy/manager.py", line 87, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/pluggy/manager.py", line 81, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/pluggy/callers.py", line 81, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/pytestqt/plugin.py", line 228, in pytest_configure
INTERNALERROR>     QtBot._inject_qtest_methods()
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/pytestqt/qtbot.py", line 645, in _inject_qtest_methods
INTERNALERROR>     method = create_qtest_proxy_method(method_name)
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/pytestqt/qtbot.py", line 624, in create_qtest_proxy_method
INTERNALERROR>     functools.update_wrapper(result, qtest_method)
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/functools.py", line 32, in update_wrapper
INTERNALERROR>     for attr in assigned:
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/shiboken2/files.dir/shibokensupport/signature/parser.py", line 286, in pyside_type_init
INTERNALERROR>     update_mapping()
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/shiboken2/files.dir/shibokensupport/signature/mapping.py", line 233, in update
INTERNALERROR>     candidates = list(mod_name for mod_name in sys.modules
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/shiboken2/files.dir/shibokensupport/signature/mapping.py", line 233, in <genexpr>
INTERNALERROR>     candidates = list(mod_name for mod_name in sys.modules
INTERNALERROR> RuntimeError: dictionary changed size during iteration
The command "pytest -v tests" exited with 3.
```
