### ISSUE TITLE
error happens when I run labelme_json_to_dataset

### ISSUE THREAD

**Issue by zhangfanqie** [wkentaro/labelme#5]
```
I cd into my folder where include image files and its corresponding  json files(built success)
But error happens when I run  labelme_json_to_dataset imageName.json in the terminal

OS:ubuntu 14.04

Traceback (most recent call last):
  File "/usr/local/bin/labelme_json_to_dataset", line 45, in <module>
    main()
  File "/usr/local/bin/labelme_json_to_dataset", line 27, in main
    img = utils.img_b64_to_array(data['imageData'])
  File "/usr/local/lib/python2.7/dist-packages/labelme/utils.py", line 36, in img_b64_to_array
    img_arr = np.array(PIL.Image.open(f))
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 2028, in open
    raise IOError("cannot identify image file")
IOError: cannot identify image file

Is this a bug of the source code?
```

**Comment by wkentaro** [comment]
Have you tried with the sample jso filen?
https://github.com/wkentaro/labelme/blob/master/_static/IMG_6319.json

**Comment by zhangfanqie** [comment]
Yes,I've tried your sample,but got the same error.
I tried to debug and build a project in PyCharm IDE ,but I got this

> Traceback (most recent call last):
  File "/home/zhangfan/download/pycharm-community-2017.1.2/helpers/pydev/pydevd.py", line 1574, in <module>
    apply_debugger_options(setup)
  File "/home/zhangfan/download/pycharm-community-2017.1.2/helpers/pydev/pydevd.py", line 1408, in apply_debugger_options
    enable_qt_support(setup_options['qt-support'])
  File "/home/zhangfan/download/pycharm-community-2017.1.2/helpers/pydev/pydevd.py", line 1065, in enable_qt_support
    pydev_monkey_qt.patch_qt(qt_support_mode)
  File "/home/zhangfan/download/pycharm-community-2017.1.2/helpers/pydev/_pydev_bundle/pydev_monkey_qt.py", line 57, in patch_qt
    import PyQt5.QtCore  # @UnresolvedImport
RuntimeError: the sip module implements API v11.0 but the PyQt5.QtCore module requires API v11.3

I follow the instruction you show,but why there's pyqt5.qtcore as above instead pyqt4.I'm really confused.
I try to use labelme to get label files which will be used in mxnet, fcn to train my datasets.Is there other solutions to process image to do image segmentation

**Comment by wkentaro** [comment]
It may be problem with integration with PyCharm IDE, and I'm not sure how to fix it.
You can try on command line or cleaned ubuntu 14.04 if you already installed pyqt5.

**Comment by wkentaro** [comment]
Please request of reopening if someone encounters this problem again.
