### ISSUE TITLE
ubuntu16.04  Annaconda3 install labelme, Run Error!!!

### ISSUE THREAD

**Issue by blakeliu** [wkentaro/labelme#50]
conda create --name=labelme python=2.7
source activate labelme
conda install pyqt
conda install numpy
pip install labelme

**
(labelme) wjy@wjy-Z270X-UD3:~$ pip install labelme
Collecting labelme
Requirement already satisfied: scipy in ./anaconda3/lib/python3.5/site-packages (from labelme)
Requirement already satisfied: Pillow>=2.8.0 in ./anaconda3/lib/python3.5/site-packages (from labelme)
Requirement already satisfied: PyYAML in ./anaconda3/lib/python3.5/site-packages (from labelme)
Requirement already satisfied: matplotlib in ./anaconda3/lib/python3.5/site-packages (from labelme)
Requirement already satisfied: six in ./anaconda3/lib/python3.5/site-packages (from labelme)
Requirement already satisfied: olefile in ./anaconda3/lib/python3.5/site-packages (from Pillow>=2.8.0->labelme)
Requirement already satisfied: numpy>=1.7.1 in ./anaconda3/lib/python3.5/site-packages (from matplotlib->labelme)
Requirement already satisfied: python-dateutil in ./anaconda3/lib/python3.5/site-packages (from matplotlib->labelme)
Requirement already satisfied: pytz in ./anaconda3/lib/python3.5/site-packages (from matplotlib->labelme)
Requirement already satisfied: cycler>=0.10 in ./anaconda3/lib/python3.5/site-packages (from matplotlib->labelme)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 in ./anaconda3/lib/python3.5/site-packages (from matplotlib->labelme)
Installing collected packages: labelme

**
(labelme) wjy@wjy-Z270X-UD3:~$ labelme
Traceback (most recent call last):
  File "/home/wjy/anaconda3/envs/labelme/bin/labelme", line 7, in <module>
    from labelme.app import main
  File "/home/wjy/anaconda3/envs/labelme/lib/python2.7/site-packages/labelme/__init__.py", line 1, in <module>
    from labelme import utils
  File "/home/wjy/anaconda3/envs/labelme/lib/python2.7/site-packages/labelme/utils.py", line 8, in <module>
    import matplotlib.pyplot as plt
  File "/home/wjy/anaconda3/lib/python3.5/site-packages/matplotlib/__init__.py", line 122, in <module>
    from matplotlib.cbook import is_string_like, mplDeprecation, dedent, get_label
  File "/home/wjy/anaconda3/lib/python3.5/site-packages/matplotlib/cbook.py", line 32, in <module>
    import numpy as np
  File "/home/wjy/anaconda3/lib/python3.5/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/home/wjy/anaconda3/lib/python3.5/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/wjy/anaconda3/lib/python3.5/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/home/wjy/anaconda3/lib/python3.5/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/home/wjy/anaconda3/lib/python3.5/site-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: cannot import name multiarray

**Comment by wkentaro** [comment]
It seems you have error while importing `numpy`, so please check if you successfully installed it.
