### ISSUE TITLE
OSError: cannot write mode RGBX as PNG 

### ISSUE THREAD

**Issue by aravindchaluvadi** [wkentaro/labelme#510]
When i type labelme and open a folder which contains images in the tool i am not able to see the image and the following error is occuring.

ERROR :

Gtk-Message: 15:04:42.933: GtkDialog mapped without a transient parent. This is discouraged.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/PIL/PngImagePlugin.py", line 725, in _save
    rawmode, mode = _OUTMODES[mode]
KeyError: 'RGBX'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/labelme/app.py", line 917, in fileSelectionChanged
    self.loadFile(filename)
  File "/usr/local/lib/python3.6/dist-packages/labelme/app.py", line 1221, in loadFile
    self.imageData = LabelFile.load_image_file(filename)
  File "/usr/local/lib/python3.6/dist-packages/labelme/label_file.py", line 50, in load_image_file
    image_pil.save(f, format=format)
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 1935, in save
    save_handler(self, fp, filename)
  File "/usr/lib/python3/dist-packages/PIL/PngImagePlugin.py", line 727, in _save
    raise IOError("cannot write mode %s as PNG" % mode)
OSError: cannot write mode RGBX as PNG
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/PIL/PngImagePlugin.py", line 725, in _save
    rawmode, mode = _OUTMODES[mode]
KeyError: 'RGBX'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/labelme/app.py", line 917, in fileSelectionChanged
    self.loadFile(filename)
  File "/usr/local/lib/python3.6/dist-packages/labelme/app.py", line 1221, in loadFile
    self.imageData = LabelFile.load_image_file(filename)
  File "/usr/local/lib/python3.6/dist-packages/labelme/label_file.py", line 50, in load_image_file
    image_pil.save(f, format=format)
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 1935, in save
    save_handler(self, fp, filename)
  File "/usr/lib/python3/dist-packages/PIL/PngImagePlugin.py", line 727, in _save
    raise IOError("cannot write mode %s as PNG" % mode)
OSError: cannot write mode RGBX as PNG
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/PIL/PngImagePlugin.py", line 725, in _save
    rawmode, mode = _OUTMODES[mode]
KeyError: 'RGBX'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/labelme/app.py", line 917, in fileSelectionChanged
    self.loadFile(filename)
  File "/usr/local/lib/python3.6/dist-packages/labelme/app.py", line 1221, in loadFile
    self.imageData = LabelFile.load_image_file(filename)
  File "/usr/local/lib/python3.6/dist-packages/labelme/label_file.py", line 50, in load_image_file
    image_pil.save(f, format=format)
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 1935, in save
    save_handler(self, fp, filename)
  File "/usr/lib/python3/dist-packages/PIL/PngImagePlugin.py", line 727, in _save
    raise IOError("cannot write mode %s as PNG" % mode)
OSError: cannot write mode RGBX as PNG

**Comment by wkentaro** [comment]
Seems image format is non-standard.
