### ISSUE TITLE
Mask generation from json not working for grayscale images

### ISSUE THREAD

**Issue by lneeraj97** [wkentaro/labelme#574]
My images are in grayscale, and when I run 
`python labelme2voc.py emails data_annotated_voc --labels labels.txt`,
it throws an error AssertionError: rgb must be 3 dimensional
```Creating dataset: data_annotated_voc
class_names: ('_background_', 'from_address', 'to_address', 'subject', 'time')
Saved class_names: data_annotated_voc/class_names.txt
Generating dataset from: emails/email0.json
Traceback (most recent call last):
  File "labelme2voc.py", line 105, in <module>
    main()
  File "labelme2voc.py", line 96, in main
    img=imgviz.rgb2gray(img),
  File "/home/neeraj/miniconda3/envs/ml/lib/python3.7/site-packages/imgviz/color.py", line 19, in rgb2gray
    assert rgb.ndim == 3, 'rgb must be 3 dimensional'
AssertionError: rgb must be 3 dimensional ```

**Comment by lneeraj97** [comment]
https://github.com/wkentaro/labelme/blob/94b4265740fd25399735a0ab4945ca0d524242fc/examples/semantic_segmentation/labelme2voc.py#L96

This was the line throwing the error. As my images are grayscale and don't need conversion to grayscale, I commented that line. Now its working fine

**Comment by lneeraj97** [comment]
It throws a different error now.
``` Creating dataset: temp_voc
class_names: ('_background_', 'from_address', 'to_address', 'subject', 'time', 'cc')
Saved class_names: temp_voc/class_names.txt
Generating dataset from: temp/email112.json
Traceback (most recent call last):
  File "labelme2voc.py", line 105, in <module>
    main()
  File "labelme2voc.py", line 89, in main
    labelme.utils.lblsave(out_png_file, lbl)
  File "/home/neeraj/miniconda3/envs/ml/lib/python3.7/site-packages/labelme/utils/_io.py", line 14, in lblsave
    if lbl.min() >= -1 and lbl.max() < 255:
AttributeError: 'tuple' object has no attribute 'min'
```
Any idea what's causing the error?

**Comment by lneeraj97** [comment]
Creating visualizations of segmentation class is what's causing the problem. So, I've commented that block out. 
https://github.com/wkentaro/labelme/blob/94b4265740fd25399735a0ab4945ca0d524242fc/examples/semantic_segmentation/labelme2voc.py#L93-L101

Realised later that there's a CLI option for it (--noviz). In conclusion, using --noviz option runs the program without any errors
