### ISSUE TITLE
AttributeError: Module 'labelsme.utils' has no attribute 'draw_label'

### ISSUE THREAD

**Issue by Ehtasha** [wkentaro/labelme#646]
Thanks fro this great tool. I'm willing to use this tool for semantic segmentation. Tool is install and I have saved JSON file after the annotation. But whenever I run this bellow command to generate mask image from annotated image. It gives me this error.

`labelme_draw_label_png C:\Users\Lenovo\Desktop\custom_nails_dataset\01\01.png`

**To Reproduce**
1. Annotate image and save it
2. Open annoconda prompt and run bellow two commands
 1.  `activate labelme`
 2.   `labelme_draw_label_png C:\Users\Lenovo\Desktop\custom_nails_dataset\01\01.png`

3. See error:   AttributeError: Module 'labelsme.utils' has no attribute 'draw_label'

**Expected behavior**
Generate mask image and label txt file.

**Screenshots**
![Uploading image.png…]()

**Desktop**
 - Windows
 - Labelme Version [4.2.10]

**Comment by keshasha** [comment]
This is because draw_label_png.py has not updated with imgviz.
I requested a pull.

**Comment by namangoy** [comment]
Still, the issue is present in the latest conda install,
```
>>> import labelme
>>> labelme.utils.draw_label
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'labelme.utils' has no attribute 'draw_label'
>>> labelme.__version__
'3.21.1'
>>> exit()
```

```
2020-05-20 17:33:35.357 python[9253:124484] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to (null)
Traceback (most recent call last):
  File "/Users/naman/miniconda3/envs/py3/bin/labelme_draw_label_png", line 11, in <module>
    sys.exit(main())
  File "/Users/naman/miniconda3/envs/py3/lib/python3.7/site-packages/labelme/cli/draw_label_png.py", line 17, in main
    lbl = np.asarray(PIL.Image.open(args.label_png))
  File "/Users/naman/miniconda3/envs/py3/lib/python3.7/site-packages/PIL/Image.py", line 2843, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'out/img.png'
```

Please release a new fix version to conda-forge
