### ISSUE TITLE
[BUG] AttributeError: Module 'labelme.utils' has no attribute 'draw_label'

### ISSUE THREAD

**Issue by namangoy** [wkentaro/labelme#662]
#646 the issue is still present in the latest conda install,
```
>>> import labelme
>>> labelme.utils.draw_label
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'labelme.utils' has no attribute 'draw_label'
>>> labelme.__version__
'3.21.1'
>>> exit()
```

```
2020-05-20 17:33:35.357 python[9253:124484] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to (null)
Traceback (most recent call last):
  File "/Users/naman/miniconda3/envs/py3/bin/labelme_draw_label_png", line 11, in <module>
    sys.exit(main())
  File "/Users/naman/miniconda3/envs/py3/lib/python3.7/site-packages/labelme/cli/draw_label_png.py", line 17, in main
    lbl = np.asarray(PIL.Image.open(args.label_png))
  File "/Users/naman/miniconda3/envs/py3/lib/python3.7/site-packages/PIL/Image.py", line 2843, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'out/img.png'
```

Please release a new fix version to conda-forge

**Comment by Zhang-O** [comment]
I also encounter this problem.There is no draw.py in the directory of "utils".

**Comment by wkentaro** [comment]
This has been fixed https://github.com/conda-forge/labelme-feedstock/pull/23. You can now install v4.2.10.
