### ISSUE TITLE
[Feature] Method to convert annotated images to COCO panoptic dataset

### ISSUE THREAD

**Issue by cclo-astri** [wkentaro/labelme#667]
Hi ,

I could use the python provided (`instance_segmentation/labelme2coco.py`) to convert my own images to MS COCO format and import to detectron2 for training and eval. 

I wonder if there exists a example script to convert the annotated images to COCO panoptic dataset format.

Please help. 

Thanks.

**Comment by EMCP** [comment]
please append a link to this panoptic format you're talking about

**Comment by EMCP** [comment]
also, did you get that script cited `labelme2coco.py` to work for you ? 

I am seeing errors

**Comment by TemitopeOladokun** [comment]
Hello @latticetower  and @EMCP , 
I am presently using [labelme2coco.py](url) but I have some errors.

save coco json
Traceback (most recent call last):
  File "/content/labelme2coco/labelme2coco.py", line 163, in <module>
    labelme2coco(labelme_json, args.output)
  File "/content/labelme2coco/labelme2coco.py", line 27, in __init__
    self.save_json()
  File "/content/labelme2coco/labelme2coco.py", line 137, in save_json
    self.data_transfer()
  File "/content/labelme2coco/labelme2coco.py", line 33, in data_transfer
    self.images.append(self.image(data, num))
  File "/content/labelme2coco/labelme2coco.py", line 51, in image
    img = utils.img_b64_to_arr(data["imageData"])
  File "/usr/local/lib/python3.6/dist-packages/labelme/utils/image.py", line 18, in img_b64_to_arr
    img_data = base64.b64decode(img_b64)
  File "/usr/lib/python3.6/base64.py", line 80, in b64decode
    s = _bytes_from_decode_data(s)
  File "/usr/lib/python3.6/base64.py", line 46, in _bytes_from_decode_data
    "string, not %r" % s.__class__.__name__) from None
TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'

Is this error thesame with yours?

**Comment by cclo-astri** [comment]
@EMCP , @deepseek 

COCO Panoptic format
[http://cocodataset.org/#format-data](url)

Corresponding API repo
[https://github.com/cocodataset/panopticapi](url)

But as I am a newbie of python, I really need some help to make use of these APIs.

Thanks.

**Comment by wshilaji** [comment]
Have you solved this problem？can you teach me?

**Comment by cclo-astri** [comment]
@wshilaji 

No, I still waiting for solution. 

Sorry.

**Comment by wshilaji** [comment]
> @wshilaji
> 
> No, I still waiting for solution.
> 
> Sorry.

I'm learning cocoapi and the file format of coco panoptic dataset.
I think I can solve this problem this week
If successful, I will send you my python file script

**Comment by ShengkaiWu** [comment]
@wshilaji Can you convert annotated images to COCO panoptic datasets?

**Comment by wshilaji** [comment]
> @wshilaji Can you convert annotated images to COCO panoptic datasets?

https://github.com/wshilaji/panoptic_coco_scipt     star  it  Thanks
