### ISSUE TITLE
No Qt bindings could be found

### ISSUE THREAD

**Issue by jhaggle** [wkentaro/labelme#668]
Trying to run lable_me_to_voc.py.
Gets the following error:

Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import labelme
Traceback (most recent call last):
  File "/home/johan/Documents/virtualenvs/labelme/lib/python3.6/site-packages/qtpy/__init__.py", line 204, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/johan/Documents/virtualenvs/labelme/lib/python3.6/site-packages/labelme/__init__.py", line 6, in <module>
    from qtpy import QT_VERSION
  File "/home/johan/Documents/virtualenvs/labelme/lib/python3.6/site-packages/qtpy/__init__.py", line 210, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found

**Comment by wkentaro** [comment]
In venv, you need to copy pyqt5 to your site-packages.

**Comment by mkt1412** [comment]
> In venv, you need to copy pyqt5 to your site-packages.

I'm facing the same issue, could you provide a detailed explanation. Thanks!

**Comment by vic1309** [comment]
Any luck?
