### ISSUE TITLE
labelme2coco.py not clear error messages, and cannot handle certain images[BUG]

### ISSUE THREAD

**Issue by EMCP** [wkentaro/labelme#671]
**Describe the bug**
the assertion regarding `__ignore__` missing from `labels.txt` is very unclear.. 

**To Reproduce**
1. Create a folder with an annotated image and its annotation
2. create a labels.txt, minus the `__ingore__`
3. try to convert to COCO

```
Traceback (most recent call last):
  File "labelme2coco.py", line 165, in <module>
    main()
  File "labelme2coco.py", line 74, in main
    assert class_name == '__ignore__'
AssertionError
```
4. then fix that by adding the `__ignore__`
5. retry to convert to COCO
6. Get an error about converting images

```
Traceback (most recent call last):
  File "/anaconda3/envs/labelme/lib/python3.7/site-packages/PIL/JpegImagePlugin.py", line 612, in _save
    rawmode = RAWMODE[im.mode]
KeyError: 'RGBA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "labelme2coco.py", line 165, in <module>
    main()
  File "labelme2coco.py", line 96, in main
    PIL.Image.fromarray(img).save(out_img_file)
  File "/anaconda3/envs/labelme/lib/python3.7/site-packages/PIL/Image.py", line 2134, in save
    save_handler(self, fp, filename)
  File "/anaconda3/envs/labelme/lib/python3.7/site-packages/PIL/JpegImagePlugin.py", line 614, in _save
    raise OSError("cannot write mode %s as JPEG" % im.mode)
OSError: cannot write mode RGBA as JPEG

```

**Expected behavior**
It isn't very clear here how to fix this error/assertion
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina
 - Labelme Version 4.4.0s

**Additional context**

**Comment by EMCP** [comment]
I am unclear why does it need to write the file?  Why not simply copy the image ?
