### ISSUE TITLE
labelme crash when using brightness / contrast tool

### ISSUE THREAD

**Issue by jorgenporgen** [wkentaro/labelme#743]
labelme crash when using brightness / contrast tool. The following error message is pasted below:

_**_[INFO   ] __init__:get_config:71 - Loading config file from: /home/user.labelmerc
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.7/site-packages/labelme/widgets/brightness_contrast_dialog.py", line 33, in onNewValue
    img = PIL.ImageEnhance.Brightness(img).enhance(brightness)
  File "/home/user/anaconda3/lib/python3.7/site-packages/PIL/ImageEnhance.py", line 36, in enhance
    return Image.blend(self.degenerate, self.image, factor)
  File "/home/user/anaconda3/lib/python3.7/site-packages/PIL/Image.py", line 2974, in blend
    return im1._new(core.blend(im1.im, im2.im, alpha))
ValueError: image has wrong mode_**_

The images are a series of .png images, 512 x 512 in size.

labelme 4.5.6
LSB Version:	core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

**Comment by hubutui** [comment]
I got the same error. Is your image 16bit? labelme use `PIL.Enhance` for brightness and contrast adjustment. But is seems that it could not deal with 16bit images.

**Comment by wkentaro** [comment]
Can you provide an example image to reproduce this?

**Comment by sofienbensayadia** [comment]
labelme crash when using brightness / contrast tool for RGBA image (32 bit)

**Comment by sunxijunjun** [comment]
I got the same error.

**Comment by wkentaro** [comment]
this should be resolved by https://github.com/wkentaro/labelme/pull/1655 and labelme==5.9.0, so closing. thanks
