### ISSUE TITLE
[BUG] TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by advanpix** [wkentaro/labelme#779]
The labelme crashes on the 1115 line with the following error message:

```
Traceback (most recent call last):
  File "c:\programdata\anaconda3\envs\labelme\lib\site-packages\labelme\app.py", line 1307, in newShape
    self.addLabel(shape)
  File "c:\programdata\anaconda3\envs\labelme\lib\site-packages\labelme\app.py", line 1115, in addLabel
    r, g, b = rgb
TypeError: 'NoneType' object is not iterable

```

It happens in any situation - trying to create new shape or loading existing annotations, etc.

The issue is that https://github.com/wkentaro/labelme/pull/695 removed following two lines:
```
        rgb = self._get_rgb_by_label(shape.label)

        if rgb is None:  <-- removed in 695
            return           <-- removed in 695

        r, g, b = rgb
```

If we put these lines back - crash is fixed and labelme works normally. Please fix this.

**Comment by advanpix** [comment]
I am using the newest labelme 4.5.6 installed through Anaconda on Windows:

```
conda create --name=labelme python=3.6
conda activate labelme
pip install labelme
```
