### ISSUE TITLE
My gray_dtype is int32 howto  be np.uint8

### ISSUE THREAD

**Issue by ghost** [wkentaro/labelme#828]
[WARNING] json_to_dataset:main:15 - This script is aimed to demonstrate how to convert the JSON file to a single image dataset.
[WARNING] json_to_dataset:main:19 - It won't handle multiple JSON files to generate a real-use dataset.
===============gray.dtype:  int32
Traceback (most recent call last):
  File "C:\Users\ben12\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts\labelme_json_to_dataset-script.py", line 33, in <module>       
    sys.exit(load_entry_point('labelme==4.5.6', 'console_scripts', 'labelme_json_to_dataset')())
  File "C:\Users\ben12\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\labelme\cli\json_to_dataset.py", line 65, in main        
    lbl_viz = imgviz.label2rgb(
  File "C:\Users\ben12\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\imgviz\label.py", line 105, in label2rgb
    img = color_module.gray2rgb(img)
  File "C:\Users\ben12\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\imgviz\color.py", line 47, in gray2rgb
    assert gray.dtype == np.uint8, "gray dtype must be np.uint8"
AssertionError: gray dtype must be np.uint8
The directory is deleted successfully
結束開始
PS C:\Users\ben12\Desktop\Work\醫放系> & C:/Users/ben12/AppData/Local/Microsoft/WindowsApps/python.exe c:/Users/ben12/Desktop/Work/醫放系/data_ok/benign_label/tt.py
開始
C:\Users\ben12\Desktop\Work\醫放系\data_ok\benign_label\A_1123_1.LEFT_CC.json
[WARNING] json_to_dataset:main:15 - This script is aimed to demonstrate how to convert the JSON file to a single image dataset.
[WARNING] json_to_dataset:main:19 - It won't handle multiple JSON files to generate a real-use dataset.
===============gray.dtype:  int32
Traceback (most recent call last):
  File "C:\Users\ben12\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts\labelme_json_to_dataset-script.py", line 33, in <module>       
    sys.exit(load_entry_point('labelme==4.5.6', 'console_scripts', 'labelme_json_to_dataset')())
  File "C:\Users\ben12\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\labelme\cli\json_to_dataset.py", line 65, in main        
    lbl_viz = imgviz.label2rgb(
  File "C:\Users\ben12\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\imgviz\label.py", line 105, in label2rgb
    img = color_module.gray2rgb(img)
  File "C:\Users\ben12\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\imgviz\color.py", line 47, in gray2rgb
    assert gray.dtype == np.uint8, "gray dtype must be np.uint8"
AssertionError: gray dtype must be np.uint8
The directory is deleted successfully

**Comment by wkentaro** [comment]
Can you explain what do you want to achieve in more detail?
