### ISSUE TITLE
Ignore a label in json file 

### ISSUE THREAD

**Issue by arnaldododo** [wkentaro/labelme#848]
Hi, I did what you say but got an error 

Traceback (most recent call last):
  File "labelme2voc.py", line 139, in <module>
    main()
  File "labelme2voc.py", line 102, in main
    cls, ins = labelme.utils.shapes_to_label(
  File "/Users/azzz/.pyenv/versions/3.8.3/lib/python3.8/site-packages/labelme/utils/shape.py", line 69, in shapes_to_label
    cls_id = label_name_to_value[cls_name]
KeyError: 'truck'

truck is the label I want to ignore

----------
You can change the content of `labels.txt`.
_Originally posted by @wkentaro in https://github.com/wkentaro/labelme/issues/447#issuecomment-511858124_

**Comment by KeijiroTajima** [comment]
Hi, I have the same error, too.

Traceback (most recent call last):
  File "./labelme2voc.py", line 106, in <module>
    main()
  File "./labelme2voc.py", line 88, in main
    label_name_to_value=class_name_to_id,
  File "/Users/tajimakeijiro/anaconda3/envs/labelme/lib/python3.6/site-packages/labelme/utils/shape.py", line 68, in shapes_to_label
    cls_id = label_name_to_value[cls_name]
KeyError: 'wall'

I wanted to ignore the class 'wall', so I removed it from labels.txt.
But I got this error.

**Comment by wkentaro** [comment]
Ah, maybe the previous solution won't work and you need to edit labelme2voc.py.
