### ISSUE TITLE
[BUG]? TypeError: arguments did not match any overloaded call

### ISSUE THREAD

**Issue by louweijia** [wkentaro/labelme#849]
run labelme, open a json file(gen for labelme 3.9.0), then have TypeError: arguments did not match any overloaded call.

print error:
[33m[WARNING][0m Skipping unexpected key in config: keep_prev_scale ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: keep_prev_brightness ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: keep_prev_contrast ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: logger_level ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: label_flags ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: default_shape_color ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: shape_color ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: shift_auto_shape_color ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: label_colors ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: shape ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: canvas ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: delete_file ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: add_point_to_edge ([1m__init__.py[0m:18)
Traceback (most recent call last):
  File "d:\programdata\anaconda3\envs\label\lib\site-packages\labelme\app.py", line 1308, in openFile
    self.loadFile(filename)
  File "d:\programdata\anaconda3\envs\label\lib\site-packages\labelme\app.py", line 1163, in loadFile
    self.loadLabels(self.labelFile.shapes)
  File "d:\programdata\anaconda3\envs\label\lib\site-packages\labelme\app.py", line 900, in loadLabels
    shape.addPoint(QtCore.QPoint(x, y))
TypeError: arguments did not match any overloaded call:
  QPoint(): too many arguments
  QPoint(int, int): argument 1 has unexpected type 'str'
  QPoint(QPoint): argument 1 has unexpected type 'str'

enviroment:
 - OS: WIndows 10
 - Labelme Version 3.9.0
blas                      1.0                         mkl  
bzip2                     1.0.6                    vc14_3  
certifi                   2016.2.28                py36_0  
cycler                    0.10.0                   py36_0  
freetype                  2.5.5                    vc14_2  
icu                       57.1                     vc14_0  
jpeg                      9b                       vc14_0  
labelme                   3.9.0                    pypi_0  
libpng                    1.6.30                   vc14_1  
libtiff                   4.0.6                    vc14_3  
matplotlib                2.0.2               np113py36_0  
mkl                       2017.0.3                      0  
numpy                     1.13.1                   py36_0  
olefile                   0.44                     py36_0  
openssl                   1.0.2l                   vc14_0  
pillow                    4.2.1                    py36_0  
pip                       21.0.1                   pypi_0  
pyparsing                 2.2.0                    py36_0  
pyqt                      5.6.0                    py36_2  
python                    3.6.2                         0  
python-dateutil           2.6.1                    py36_0  
pytz                      2017.2                   py36_0  
pyyaml                    3.12                     py36_0  
qt                        5.6.2                    vc14_6  
qtpy                      1.3.1                    py36_0  
setuptools                36.4.0                   py36_1  
sip                       4.18                     py36_0  
six                       1.10.0                   py36_0  
termcolor                 1.1.0                    py36_0  
tk                        8.5.18                   vc14_0  
vc                        14                            0  
vs2015_runtime            14.0.25420                    0  
wheel                     0.29.0                   py36_0  
wincertstore              0.2                      py36_0  
zlib                      1.2.11                   vc14_0  

others:
i try all operation with labelme-3.16.7/4.5.7, the issue also exist.

**Comment by louweijia** [comment]
I have solved the problem, Amend as follows.
in app.py:
shape.addPoint(QtCore.QPoint(x, y)) ===> shape.addPoint(QtCore.QPoint(float(x), float(y)))
