### ISSUE TITLE
labelme_json_to_dataset __array__() error

### ISSUE THREAD

**Issue by Xelach** [wkentaro/labelme#880]
Hello,

I wanted to create a mask via the command: labelme_json_to_dataset pic1.json -o pic1json
The directory was created but is empty and i get the error message: 
TypeError: __array__() takes 1 positional argument but 2 were given

You got any Ideas what the issue is? 

BR,
Xelach

**Comment by abbas-tari** [comment]
This happens for me when I want to convert to coco format for example!!

**Comment by Adie-** [comment]
Same issue for me for both 'labelme_json_to_dataset' and 'labelme_draw_json'

Full error output:
```
Traceback (most recent call last):
  File "\LabelMe_Annotator\venv\Scripts\labelme_draw_json-script.py", line 33, in <module>
    sys.exit(load_entry_point('labelme==4.5.9', 'console_scripts', 'labelme_draw_json')())
  File "\LabelMe_Annotator\venv\lib\site-packages\labelme\cli\draw_json.py", line 32, in main
    lbl, _ = utils.shapes_to_label(
  File "\LabelMe_Annotator\venv\lib\site-packages\labelme\utils\shape.py", line 71, in shapes_to_label
    mask = shape_to_mask(img_shape[:2], points, shape_type)
  File "\LabelMe_Annotator\venv\lib\site-packages\labelme\utils\shape.py", line 47, in shape_to_mask
    mask = np.array(mask, dtype=bool)

TypeError: __array__() takes 1 positional argument but 2 were given
```

**Comment by Xelach** [comment]
That was the fix for me. Thanks!

**Comment by S0ngZ1Chen** [comment]
Hi! This is my problem,could you help me?
[errer.txt](https://github.com/wkentaro/labelme/files/11296325/errer.txt)
