### ISSUE TITLE
[BUG] json_to_dataset: UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 9918: illegal multibyte sequence

### ISSUE THREAD

**Issue by haiduo** [wkentaro/labelme#922]
**Describe the bug**
the  version of labelme 4.5.11 can't convert json data to png with the command line :  labelme_json_to_dataset xxx.json -o xxx
 it as follows:

```
Traceback (most recent call last):
  File "d:\anaconda3\envs\labelme_11\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda3\envs\labelme_11\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\anaconda3\envs\labelme_11\Scripts\labelme_json_to_dataset.exe\__main__.py", line 7, in <module>
  File "d:\anaconda3\envs\labelme_11\lib\site-packages\labelme\cli\json_to_dataset.py", line 39, in main
    data = json.load(open(json_file))
  File "d:\anaconda3\envs\labelme_11\lib\json\__init__.py", line 296, in load
    return loads(fp.read(),
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 9918: illegal multibyte sequence
```

**Comment by wkentaro** [comment]
Can you please provide image / json file to reproduce this?

**Comment by haiduo** [comment]
> Can you please provide image / json file to reproduce this?
ok, but I have solved it.  Because it only can't process filepath of including simplified Chinese.
