### ISSUE TITLE
[BUG] "IndexError: list index out of range" when edit label

### ISSUE THREAD

**Issue by hoozh** [wkentaro/labelme#963]
**Describe the bug**
label crashed when edit label.

**To Reproduce**
1. Load Labelme
2. Click "Open Dir"
3. Check "Save Automatically"

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - Labelme Version [e.g. 4.2.9]

**Additional context**

**Comment by ShuaiLYU** [comment]
I have met the same bug. have you found a solution?

**Comment by hoozh** [comment]
> I have met the same bug. have you found a solution?

try another version

**Comment by floyddcn** [comment]
Latest version 5.0.1 still has the crash problem when changing existing label value to a non-existing string value.
For me,the only choice seems to be a fallback to 4.2.10 is Ok

**Comment by shihaoyin** [comment]
> Latest version 5.0.1 still has the crash problem when changing existing label value to a non-existing string value.
> For me,the only choice seems to be a fallback to 4.2.10

Have you solve the crash problem when editing labels？

**Comment by happyamyhope** [comment]
> **Describe the bug** labelme crashed when edit label.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Load Labelme
> 2. Click "Open Dir"
> 3. Check "Save Automatically"
> 4. Uncheck "Save With Image Data"
> 5. Check "Keep Previous Annotation"
> 6. Select last image in _**File List**_, and annotate it with a label
> 7. Press A to open previous image,
> 8. Edit the label
> 9. Labelme crashed.
> 
> **Expected behavior** Label can be updated.
> 
> **Screenshots**
> 
> ```
> Traceback (most recent call last):
>   File "D:\Anaconda3\envs\labelme_env\lib\site-packages\labelme\app.py", line 1083, in editLabel
>     self._update_shape_color(shape)
>   File "D:\Anaconda3\envs\labelme_env\lib\site-packages\labelme\app.py", line 1163, in _update_shape_color
>     r, g, b = self._get_rgb_by_label(shape.label)
>   File "D:\Anaconda3\envs\labelme_env\lib\site-packages\labelme\app.py", line 1173, in _get_rgb_by_label
>     item = self.uniqLabelList.findItemsByLabel(label)[0]
> IndexError: list index out of range
> ```
> 
> **Desktop (please complete the following information):**
> 
> * OS: `Windows 10`
> * Labelme Version `4.6.0`
> 
> **Additional context** Labelme Version 4.2.10 is Ok

i crashed this problem today, and i will try older version.

**Comment by happyamyhope** [comment]
> fix bug in editLabel #1151

https://github.com/wkentaro/labelme/pull/1151
this work for me

**Comment by PhpEssential** [comment]
Hi you can comment this line for quick fix, it's only used to change the color of the shape

in app.py line 1075 for the version 5.0.1
in editLabel function
        #self._update_shape_color(shape)

**Comment by wkentaro** [comment]
Will be fixed by v5.0.2

```
pip install --no-cache-dir labelme==5.0.2
```
